### PR TITLE
Update to NixOS 24.11 - Vicuna :camel: 

### PR DESCRIPTION
**Pull request by kachick**
* Resolves GH-757
* Closes GH-944
* Begins to use overlay to apply hotfix easy
* Roughly updated the commented URL, it should be checked in https://github.com/kachick/dotfiles/issues/947
* Go with `release-24.11` for now, because of `nixos-24.11` does not have crucial hotfix.

---

* Read and follow
  * https://github.com/NixOS/nixpkgs/blob/8e5e5a6add04c7f1e38e76f59ada6732947f1e55/nixos/doc/manual/release-notes/rl-2411.section.md
  * https://github.com/nix-community/home-manager/blob/a46e702093a5c46e192243edbd977d5749e7f294/docs/release-notes/rl-2411.md
* In NixOS, check the error log with `nixos-rebuild build`. Don't use `switch` first
* In home-manager, check the warnings in CI
* When found issues around packages, [attempt to fix and send PR to upstream](https://github.com/NixOS/nixpkgs/pulls?q=+is%3Apr+author%3Akachick+)

### CODE REVIEW

**Comment by kachick** [comment]
:thought_balloon: Want https://github.com/kachick/dotfiles/issues/642 in these task...

**Comment by kachick** [comment]
TODO: Suppress these warnings

```console
> sudo nixos-rebuild switch --flake ".#$(hostname)" --show-trace && makers apply 'kachick@nixos-desktop'
building the system configuration...
trace: evaluation warning: The ‘gnome.epiphany’ was moved to top-level. Please use ‘pkgs.epiphany’ directly.
trace: evaluation warning: The ‘gnome.geary’ was moved to top-level. Please use ‘pkgs.geary’ directly.
trace: evaluation warning: The ‘gnome.evince’ was moved to top-level. Please use ‘pkgs.evince’ directly.
trace: evaluation warning: The ‘gnome.gnome-calendar’ was moved to top-level. Please use ‘pkgs.gnome-calendar’ directly.
trace: evaluation warning: The ‘gnome.gnome-music’ was moved to top-level. Please use ‘pkgs.gnome-music’ directly.
trace: evaluation warning: i18n.inputMethod.enabled will be removed in a future release. Please use .type, and .enable = true instead
trace: evaluation warning: The ‘gnome.dconf-editor’ was moved to top-level. Please use ‘pkgs.dconf-editor’ directly.
trace: evaluation warning: The ‘gnome.gnome-boxes’ was moved to top-level. Please use ‘pkgs.gnome-boxes’ directly.
trace: evaluation warning: The ‘gnome.mutter’ was moved to top-level. Please use ‘pkgs.mutter’ directly.
trace: evaluation warning: The ‘gnome.gnome-settings-daemon’ was moved to top-level. Please use ‘pkgs.gnome-settings-daemon’ directly.
```

**Comment by kachick** [comment]
```console
> sudo nixos-rebuild switch --flake ".#$(hostname)" --show-trace                                        
building the system configuration...
error: builder for '/nix/store/j7r84gckajykldwv700z4m3j3gp9nvj8-bazel-7.4.0.drv' failed with exit code 1;
       last 10 log lines:
       > patching file src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRuleClassProvider.java
       > Hunk #1 succeeded at 568 with fuzz 2 (offset 102 lines).
       > applying patch /nix/store/2y0fhjn87j7b22v3h8v5hxrmgbwmcn11-bazel_rc.patch
       > patching file src/main/cpp/option_processor.cc
       > applying patch /nix/store/9857sd4kzzpl1xcx81hwh98ldma58ya3-nix-hacks.patch
       > patching file src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java
       > Hunk #1 FAILED at 178.
       > Hunk #2 succeeded at 634 (offset 24 lines).
       > 1 out of 2 hunks FAILED -- saving rejects to file src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java.rej
       > patching file src/main/java/com/google/devtools/build/lib/shell/JavaSubprocessFactory.java
       For full logs, run 'nix log /nix/store/j7r84gckajykldwv700z4m3j3gp9nvj8-bazel-7.4.0.drv'.
error: 1 dependencies of derivation '/nix/store/vkzr7ymifkl2rwzzm59wxbm6q4bfv9mh-fcitx5-mozc-2.30.5544.102.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l30skrld5wdww2fyy3301yvpqj5zysny-fcitx5-with-addons-5.1.11.drv' failed to build
error: 1 dependencies of derivation '/nix/store/icq9dndhzll0fz9masm01d6kskyjd5yz-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xcq3aq080zirpsx9sqzmw8fx5q9ja423-set-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dv9vnmjfg1zhfvlwfhf5xk5xmlkyyhhg-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9sfp3658nagpr2pp65qjamzbzm3p297k-nixos-system-algae-24.11.20241116.201a24e.drv' failed to build
```

**Comment by kachick** [comment]
```
building the system configuration...
error: builder for '/nix/store/j7r84gckajykldwv700z4m3j3gp9nvj8-bazel-7.4.0.drv' failed with exit code 1;
       last 10 log lines:
       > patching file src/main/java/com/google/devtools/build/lib/bazel/rules/BazelRuleClassProvider.java
       > Hunk #1 succeeded at 568 with fuzz 2 (offset 102 lines).
       > applying patch /nix/store/2y0fhjn87j7b22v3h8v5hxrmgbwmcn11-bazel_rc.patch
       > patching file src/main/cpp/option_processor.cc
       > applying patch /nix/store/9857sd4kzzpl1xcx81hwh98ldma58ya3-nix-hacks.patch
       > patching file src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java
       > Hunk #1 FAILED at 178.
       > Hunk #2 succeeded at 634 (offset 24 lines).
       > 1 out of 2 hunks FAILED -- saving rejects to file src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java.rej
       > patching file src/main/java/com/google/devtools/build/lib/shell/JavaSubprocessFactory.java
       For full logs, run 'nix log /nix/store/j7r84gckajykldwv700z4m3j3gp9nvj8-bazel-7.4.0.drv'.
error: 1 dependencies of derivation '/nix/store/vkzr7ymifkl2rwzzm59wxbm6q4bfv9mh-fcitx5-mozc-2.30.5544.102.drv' failed to build
error: 1 dependencies of derivation '/nix/store/l30skrld5wdww2fyy3301yvpqj5zysny-fcitx5-with-addons-5.1.11.drv' failed to build
error: 1 dependencies of derivation '/nix/store/k6gh4w90hq91cqi13gvd7hqknsjcxhiv-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nxmppry1i95wann88zjfg3jwnlnwy44p-set-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9251lxal9b5hc2784qjyrqrvziqbvga8-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2gmf54rjirvp24ir842r56p4k5fp7mw9-nixos-system-algae-24.11.20241116.057f63b.drv' failed to build
```

https://github.com/NixOS/nixpkgs/pull/356802

**Comment by kachick** [comment]
On macos-13 runner

```
copying path '/nix/store/wzr76whf1n1j3gnqc6h6wfjkhmg34vrr-cargo-check-hook.sh' from 'https://cache.nixos.org/'...
building '/nix/store/ynjsnb6lj1g2y7c5adr4pd80wn0fp7li-nix-init-0.3.2.drv'...
building '/nix/store/khyg0pj0f8kr10rc5nf3nmvbzcadsvq3-selfup-v1.1.6.drv'...
error: builder for '/nix/store/ynjsnb6lj1g2y7c5adr4pd80wn0fp7li-nix-init-0.3.2.drv' failed with exit code 101;
       last 25 log lines:
       > Executing cargoSetupPostPatchHook
       > Validating consistency between /private/tmp/nix-build-nix-init-0.3.2.drv-0/source/Cargo.lock and /private/tmp/nix-build-nix-init-0.3.2.drv-0/cargo-vendor-dir/Cargo.lock
       > Finished cargoSetupPostPatchHook
       > Running phase: configurePhase
       > Running phase: buildPhase
       > Executing cargoBuildHook
       > error: failed to get `askalono` as a dependency of package `license-store-cache v0.3.2 (/private/tmp/nix-build-nix-init-0.3.2.drv-0/source/license-store-cache)`
       >
       > Caused by:
       >   failed to load source for dependency `askalono`
       >
       > Caused by:
       >   Unable to update registry `crates-io`
       >
       > Caused by:
       >   failed to update replaced source registry `crates-io`
       >
       > Caused by:
       >   failed to parse manifest at `/private/tmp/nix-build-nix-init-0.3.2.drv-0/cargo-vendor-dir/cargo-util-0.2.14/Cargo.toml`
       >
       > Caused by:
       >   error inheriting `edition` from workspace root manifest's `workspace.package.edition`
       >
       > Caused by:
       >   failed to find a workspace root
       For full logs, run 'nix log /nix/store/ynjsnb6lj1g2y7c5adr4pd80wn0fp7li-nix-init-0.3.2.drv'.
error: 1 dependencies of derivation '/nix/store/m00[771](https://github.com/kachick/dotfiles/actions/runs/11887500125/job/33123304262#step:5:772)yz0yisbbck57f6vmzzj3sygkz5-nix-shell-env.drv' failed to build
Error: Process completed with exit code 1.
```

Looks like the nix-init has been updated to 0.3.2 from 0.3.0 in NixOS 24.11 channel

**Comment by kachick** [comment]
```console
> </etc/os-release
ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20241119.3b9b505"
CPE_NAME="cpe:/o:nixos:nixos:24.11"
DEFAULT_HOSTNAME=algae
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
ID_LIKE=""
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_END="2025-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VARIANT=""
VARIANT_ID=""
VENDOR_NAME=NixOS
VENDOR_URL="https://nixos.org/"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"
```

:tada: :camel:

**Comment by osbm** [comment]
How did you fix fcitx5 error :eyes:

**Comment by kachick** [comment]
Yeah... Avoiding the issue with using unstable channel for that package :sweat_smile: https://github.com/kachick/dotfiles/pull/943/files#diff-61b40353542a498a195ae238e4f8adaf8b7b17d04cf5af03652df9189ea7a4cfR297

**Comment by osbm** [comment]
I swear i didnt copy my line from you, too similar 😭😭😭
https://github.com/osbm/nixos-configuration/blob/c656992897381779ee9f7883a9b441a478fc7b0f/common/i18n.nix#L30

**Pull request merged**
